name: programmable-api-gateway

include:
  - docker-compose.yaml

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - DEBUG=true
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ../src:/app/src:ro
